CREATE TABLE post_images (
    image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    image_url VARCHAR(500) NOT NULL,
    image_order INT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_post_images_post
        FOREIGN KEY (post_id) REFERENCES posts(post_id) ON DELETE CASCADE
);

CREATE INDEX idx_post_image_post_order
    ON post_images(post_id, image_order);

INSERT INTO post_images (post_id, image_url, image_order, created_at)
SELECT post_id, post_image, 0, COALESCE(post_created_at, CURRENT_TIMESTAMP)
FROM posts
WHERE post_image IS NOT NULL AND TRIM(post_image) <> '';

-- 호환 배포 후 애플리케이션이 post_images만 사용하는 것이 확인되면 실행:
-- ALTER TABLE posts DROP COLUMN post_image;
