# 프론트 컨테이너의 책임은 리액트의 HTML, CSS, JS 파일 제공하는 것
server {
    listen 80;
    server_name _;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
